export const ORDER_EXECUTE_FETCH = 'orders/EXECUTE_FETCH';
export const ORDER_EXECUTE_DATA = 'orders/EXECUTE_DATA';
export const ORDER_EXECUTE_ERROR = 'orders/EXECUTE_ERROR';

export const ORDERS_SET_CURRENT_PRICE = 'orders/SET_CURRENT_PRICE';
export const ORDERS_SET_AMOUNT = 'orders/SET_AMOUNT';
export const ORDERS_SET_ORDER_TYPE = 'orders/SET_ORDER_TYPE';
export const ORDERS_SET_AVAILABLE_QUOTE = 'orders/SET_AVAILABLE_QUOTE';
export const ORDERS_SET_AVAILABLE_BASE = 'orders/SET_AVAILABLE_BASE';
