import InputOtpNew from './InputOTPNew';
export { InputOtpNew };
export { Button } from './Button';
export { Input } from './Input';
export { CountDown } from './CountDown'
export { LoadingTable } from './LoadingTable';
export * from './Confirm';
export * from './InputOrder';
export * from './InputAmount';
export * from './InputCurrency';
export * from './InputNumber';
export * from './InputBeneficary';
export * from './SliderPercent';
export * from './Select';
export * from './InputGroup';
export * from './InputPhone';
export * from './Switch';
export * from './Nav';
export * from './SVGSprites';
export * from './ListDropdown';
export * from './Badge';
export * from './Export';
export * from './types';
export * from './InputOtp';
export * from './InputOtp2';
export * from './GeetestCaptchaV4';
export * from './Loader';
export * from './DropdownMenu';
export * from './Skeleton';
export * from './PageLink';
export * from './Paginations';
export * from './Checkbox';
export * from './CheckboxAlt';
export * from './AdibDropdown';
export * from './Label';
export * from './LabelAlt';
export * from './GenericSelect';
export * from './Accordion';
export * from './AccordionItem';
export * from './Listbox';
export * from './CellDetail';
export * from './PriceChart';
export * from './PriceChart2';
export * from './PriceChart3';
export * from './Image';
