export const AUTH_LOGIN_FETCH = 'auth/LOGIN_FETCH';
export const AUTH_LOGIN_DATA = 'auth/LOGIN_DATA';
export const AUTH_LOGIN_ERROR = 'auth/LOGIN_ERROR';
export const AUTH_LOGIN_REQUIRE_2FA = 'auth/LOGIN_REQUIRE_2FA';
export const AUTH_LOGIN_REQUIRE_2FA_RESET = 'auth/AUTH_LOGIN_REQUIRE_2FA_RESET';

export const AUTH_REGISTER_DATA = 'auth/REGISTER_DATA';
export const AUTH_REGISTER_FETCH = 'auth/REGISTER_FETCH';
export const AUTH_REGISTER_ERROR = 'auth/REGISTER_ERROR';
export const AUTH_REGISTER_REQUIRE_VERIFICATION =
   'auth/REGISTER_REQUIRE_VERIFICATION';

export const AUTH_VERIFICATION_FETCH = 'auth/VERIFICATION_FETCH';
export const AUTH_VERIFICATION_SUCCESS = 'auth/VERIFICATION_SUCCESS';

export const AUTH_LOGOUT_FETCH = 'auth/LOGOUT_FETCH';
export const AUTH_LOGOUT_DATA = 'auth/LOGOUT_DATA';
export const AUTH_LOGOUT_FAILURE = 'auth/LOGOUT_FAILURE';

export const AUTH_TEST_STATE = 'auth/TEST_AUTH_STATE';

export const AUTH_ENTROPY_PASSWORD_FETCH = 'auth/ENTROPY_PASSWORD_FETCH';
export const AUTH_ENTROPY_PASSWORD_DATA = 'auth/ENTROPY_PASSWORD_DATA';
export const AUTH_ENTROPY_PASSWORD_ERROR = 'auth/ENTROPY_PASSWORD_ERROR';
